CONTEXT_GENERIC = "generic"
CONTEXT_SYSTEM = "system"
CONTEXT_PATIENT = "patient"
CONTEXT_DOCTOR = "doctor"

CONTEXT_SCOPES = {
    CONTEXT_GENERIC,
    CONTEXT_SYSTEM,
    CONTEXT_PATIENT,
    CONTEXT_DOCTOR,
}
